### PR TITLE
feat: add y/n dialog before modifying rcfile

### LINKED ISSUE #34: Usual "don't modify my shell environment" issue
Common request for tools that similarly modify my env files upon installation :slightly_smiling_face:  Could yen by default not modify .bashrc/.zshrc and provide an option to opt-in? Or at least an option to opt-out that is clearly documented right above/under the curl installation line :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by tusharsadhwani**
Resolves #34

### CODE REVIEW

**Comment by tusharsadhwani** [comment]
@pawamoy can you run `install.sh` manually (download file from github / git clone whatever works) and confirm that it asks for confirmation before modification?

Ensure that `.yen/bin` isn't already in your rcfile. It should ask for confirmation before adding it in.

**Comment by pawamoy** [comment]
```console
% sh install.sh 
This script will automatically download and install yen for you.
Getting it from this url: https://github.com/tusharsadhwani/yen/releases/latest/download/yen-rs-x86_64-unknown-linux-musl
The binary will be installed into '/home/pawamoy/.yen/bin'
############################################################################################################################################################################## 100.0%
############################################################################################################################################################################## 100.0%
############################################################################################################################################################################## 100.0%
Install 'yen' in '/home/pawamoy/.zshrc'? [y/n] 
Please restart or source your shell.
```

:tada:

**Comment by tusharsadhwani** [comment]
Awesome. Simply merging this PR will change the behaviour of the `curl` command to the new behaviour. So, consider it fixed!

**Comment by pawamoy** [comment]
Ah you're too fast! I was going to suggest printing a message showing how to "source" yen when the user chooses not to modify the rc file :slightly_smiling_face: 

Something like:

```
To enable yen in you shell environment, add this command to the startup script of your choice:

export PATH="${PATH}:/home/pawamoy/.yen/bin"
```

**Comment by tusharsadhwani** [comment]
whoops

**Comment by tusharsadhwani** [comment]
I think it's fine for now as the script does mention where the binary will be put. If you think it needs improvement do send a PR.

**Comment by pawamoy** [comment]
Yes, I agree, I think it's fine too :slightly_smiling_face:

**Pull request merged**
